### ISSUE TITLE
Project user management

### ISSUE THREAD

**Issue by vanatteveldt** [ccs-amsterdam/amcat4client#2]

**Comment by damian0604** [comment]
I guess this is the issue that we talked about today @vanatteveldt .The user management page now simply says "And here should be some stuff that you show for CRUD users, role changes, ...", but I guess implementing this would be necessary to proceed testing Amcat4 with some alpha users (colleagues here for instance). Or is there another temporary workarounnd beyond sharing the admin credentials?

**Comment by vanatteveldt** [comment]
Done, I think
