### ISSUE TITLE
Error in getting aggregate statistics (summary.tsx)

### ISSUE THREAD

**Issue by mrwunderbar666** [ccs-amsterdam/amcat4client#36]
Please check out the bug caused by the index `wp3` . I have no clue about react, but now the screen is completely white, and the browser console reads as follows:

![Screenshot from 2022-11-30 15-22-04](https://user-images.githubusercontent.com/20080275/204840119-ae2157b0-5ca8-4a56-a754-4a59564850a7.png)

I cannot reproduce this error with the python client

**Comment by vanatteveldt** [comment]
I think this is fixed in the newest version?
