### ISSUE TITLE
Login not working when linking to index directly

### ISSUE THREAD

**Issue by JBGruber** [ccs-amsterdam/amcat4client#42]
When authentication is enabled and one tries access a specific index with guest access (e.g., http://localhost/h/localhost%2Famcat/i/state_of_the_union/query), this screen is shown:

![image](https://github.com/ccs-amsterdam/amcat4client/assets/23524101/d1266280-3745-4d9e-8762-a201a69c1baa)

Clicking the button does not do anything (the browser console also does not show any errors). To resolve it, the user has to manually navigate to the amcat4client address (in this case http://localhost/), log in as guest and can then  access the original URL.

**Comment by vanatteveldt** [comment]
Seems fixed in new version
