### ISSUE TITLE
date picker has no 'clear value' option

### ISSUE THREAD

**Issue by vanatteveldt** [ccs-amsterdam/amcat4client#48]
when you add a date filter, you get two 'columns' for from and to date. If you only pick a from date, it's a one-sided filter. If you then add a to date, it becomes a from - to filter. However, there seems no way to remove the 'to date' again so you only have a from filter (apart from removing the filter and re-applying it)

**Comment by kasperwelbers** [comment]
So it does work if you try turning it off and on again?

**Comment by vanatteveldt** [comment]
Also, it turns out you can actually just click on the selected value and it unselects, so seems like a user (=me) error
